apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: orderservice
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: orderservice
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orderservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
      - name: orderservice
        image: flakio/orderservice:21
        ports:
        - containerPort: 80
